### PR TITLE
RFC-422: Major updates for brand new version of LDM-230

### PR DESCRIPTION
**Pull request by mbutlerncsa**
updates for LDM-230 through the comments for the RFC-422 tickets

### CODE REVIEW

**Review by womullan — COMMENTED** [review]
There are many undefined acronyms - I made an attempt to fix them but please check at least  DPP , OSSEC, WSUS, SEIM  in myacronyms.txt
I changed one NSCA to NCSA ..  see my PR

**Review by womullan — COMMENTED** [review]
docs/L1_Services/Telemetry_Gatewaying_Service.tex   is not actually included in the document was it intended to be?    A telemetry Gateway is mentioned on page 14 and never again .. 

Should we drop the mention of it until we figure out that we really need that?   or should we put some sentences in it that it's to TBD?

**Comment by womullan** [comment]
section 2.1. is now Prompt processing .. but in the intro there is still a line on Level 1 processing for L1 products ..  on the first page I think we should make an effort for the new terminology. I pushed an suggested reword to my branch  for docs/body.tex

**Review by womullan — APPROVED** [review]
with my PR included this is ok for me -- @timj i fixed the build for acronyms.tex

**Comment by timj** [comment]
We are meant to be developing on `tickets/RFC-422` --- I need a moment to work out what's going on with this document development. When the document is released I update `master` as part of the release process.

**Review by timj — APPROVED** [review]
I've made the release.

**Pull request merged**
